"""empty message

Revision ID: a229df76f62c
Revises: 715a641401ff
Create Date: 2023-07-17 14:38:56.121608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a229df76f62c'
down_revision = '715a641401ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_gender_key', type_='unique')
        batch_op.drop_constraint('people_lastname_key', type_='unique')
        batch_op.drop_constraint('people_name_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_name_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')
        batch_op.drop_constraint('planets_size_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_size_key', ['size'])
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_name_key', ['name'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_name_key', ['name'])
        batch_op.create_unique_constraint('people_lastname_key', ['lastname'])
        batch_op.create_unique_constraint('people_gender_key', ['gender'])

    # ### end Alembic commands ###
